[project]
name = "fastapi-otp-auth"
version = "0.1.3"
description = "A simple and robust OTP (One-Time Password) authentication library for FastAPI, backed by Redis and Email."
authors = [
    {name = "Rok Sprogar", email = "rok.sprogar@gmail.com"}
]
readme = "README.md"
license = "MIT"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Development Status :: 5 - Production/Stable",
]
dependencies = [
    "fastapi>=0.119.0,<0.121.0",
    "redis[hiredis]>=7.0.1,<8.0.0",
    "fastapi-mail>=1.5.7,<2.0.0",
    "pydantic-settings>=2.0.0,<3.0.0",
    "pyjwt>=2.8.0,<3.0.0"
]

[project.urls]
Repository = "https://github.com/roksprogar/fastapi-otp-auth"
Homepage = "https://github.com/roksprogar/fastapi-otp-auth"

[dependency-groups]
dev = [
    "pytest>=8.0.0",
    "httpx>=0.27.0",
    "ruff>=0.3.0",
    "pre-commit>=3.6.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/fastapi_otp_auth"]